[package]
name = "shocs-lc"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "SHOCS LAN-local lighting controller"

[dependencies]
lifx = { git = "https://github.com/christophercurley/lifx-lan-rs", version = "0.3.1" }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "signal", "time"] }
